global_costmap:
  global_frame: map
  rabot_base_frame: /base_footprint
  transform_tolerance: 2.0
  update_frequency: 1.0
  publish_frequency: 0.0
  static_map: true
  rolling_window: false

  plugins:
    - {name: static_layer,                           type: "costmap_2d::StaticLayer"}
    - {name: global_inflation_layer,     type: "costmap_2d::InflationLayer"}

